
# SITE INFORMATION
title:        Steven Stetzler
tagline:      Astronomy Graduate Student at University of Washington
baseurl:      "/github-pages-template/"
paginate:     1
locale:       "en"

# YOUR INFORMATION
# About/contact
author:
  name: Steven Stetzler
  headshot: img/headshot.png
  social:
    - type: email
      link: steven.stetzler@mail.com
    - type: github
      link: https://github.com/stevenstetzler
    - type: researchgate
      link: https://researchgate.net/profile/Steven_Stetzler
#     - type: twitter
#       link: https://twitter.com/Twitter_Handle
    # Uncomment these to add more social icons to your site
    # - type: facebook
    #   link: https://facebook.com/StevenStetzler
    # - type: instagram
    #   link: https://instagram.com/stevenstetzler
    # - type: linkedin
    #   link: https://linkdin.com/stevenstetzler
    # - type: orcid
    #   link: https://orcid.org/id

# This adds the _pages folder to Jekyll and tells it to process and output those files
collections:
  pages:
    output: true
    permalink: /:path/

# NAVIGATION
# This determines which navigation buttons are shown on the website
# These MUST be the same as the title of the page (or the name of the file if that is not set)
nav:
  - home
  - about
  - research
  - publications

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
